import type {DesignDraft,RecentDesign,ToolSlug} from '@/lib/types';
const DB='sammemha-local';const STORE='drafts';const RECENT='sammemha:recent';const FAVORITES='sammemha:template-favorites';
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'slug'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
export async function saveDraft(draft:DesignDraft){try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(draft);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}catch{/* Progressive enhancement: editing still works when IndexedDB is blocked. */}}
export async function loadDraft(slug:ToolSlug){try{const db=await openDb();const value=await new Promise<DesignDraft|undefined>((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).get(slug);req.onsuccess=()=>resolve(req.result as DesignDraft|undefined);req.onerror=()=>reject(req.error)});db.close();return value??null}catch{return null}}
export function saveRecent(item:RecentDesign){try{const old=JSON.parse(localStorage.getItem(RECENT)||'[]') as RecentDesign[];const key=`${item.slug}:${item.templateId}`;const next=[item,...old.filter(x=>`${x.slug}:${x.templateId}`!==key)].slice(0,8);localStorage.setItem(RECENT,JSON.stringify(next))}catch{}}
export function getRecentDesigns(){try{return JSON.parse(localStorage.getItem(RECENT)||'[]') as RecentDesign[]}catch{return []}}
export function clearRecentDesigns(){try{localStorage.removeItem(RECENT)}catch{}}
export function toggleTemplateFavorite(slug:ToolSlug,templateId:string){const id=`${slug}:${templateId}`;try{const cur=new Set<string>(JSON.parse(localStorage.getItem(FAVORITES)||'[]'));if(cur.has(id))cur.delete(id);else cur.add(id);localStorage.setItem(FAVORITES,JSON.stringify([...cur]));return cur.has(id)}catch{return false}}
export function isTemplateFavorite(slug:ToolSlug,templateId:string){try{return (JSON.parse(localStorage.getItem(FAVORITES)||'[]') as string[]).includes(`${slug}:${templateId}`)}catch{return false}}
