import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import Breadcrumbs from '@/components/Breadcrumbs';
import JsonLd from '@/components/JsonLd';
import ShareButton from '@/components/ShareButton';
import ToolEditor from '@/features/editor/ToolEditor';
import ToolCard from '@/components/ToolCard';
import {tools,toolsBySlug} from '@/data/tools';
import type {ToolSlug} from '@/lib/types';
import {getSiteUrl} from '@/lib/site-url';
export function generateStaticParams(){return tools.map(t=>({slug:t.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const tool=toolsBySlug[slug as ToolSlug];if(!tool)return{};return{title:tool.name,description:tool.description,alternates:{canonical:`/tools/${tool.slug}`},openGraph:{title:`${tool.name} | صمّمها`,description:tool.description,url:`/tools/${tool.slug}`}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const tool=toolsBySlug[slug as ToolSlug];if(!tool)notFound();const related=tool.related.map(s=>toolsBySlug[s]);const base=getSiteUrl();const schema={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:tool.name,url:`${base}/tools/${tool.slug}`,applicationCategory:'DesignApplication',operatingSystem:'Web',inLanguage:'ar',offers:{"@type":"Offer",price:'0',priceCurrency:'USD'},description:tool.description},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'الرئيسية',item:base},{"@type":"ListItem",position:2,name:'الأدوات',item:`${base}/tools`},{"@type":"ListItem",position:3,name:tool.name,item:`${base}/tools/${tool.slug}`}]}]};return <div className="container"><JsonLd data={schema}/><Breadcrumbs name={tool.name}/><header className="tool-intro"><div><span className="eyebrow">{tool.category} • مجاني</span><h1>{tool.name}</h1><p>{tool.description} اختر من {tool.templates.length} {tool.templates.length===1?'قالب':'قوالب'} أصلية.</p></div><ShareButton/></header><ToolEditor tool={tool}/><section className="content-card"><h2>لماذا تستخدم هذه الأداة؟</h2><ul>{tool.benefits.map(x=><li key={x}>{x}</li>)}</ul></section><section className="content-card"><h2>طريقة الاستخدام</h2><ol><li>اختر القالب المناسب من لوحة التحكم.</li><li>أدخل بياناتك وعدّل الألوان والصور وشاهد المعاينة مباشرة.</li><li>راجع Safe Area وخيار Bleed إذا كان التصميم للطباعة.</li><li>نزّل PNG للمشاركة أو PDF للطباعة.</li></ol></section><section className="content-card faq"><h2>أسئلة شائعة</h2>{tool.faq.map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</section><section className="section"><div className="section-head"><h2>أدوات مشابهة</h2></div><div className="tools-grid">{related.map(t=><ToolCard key={t.slug} tool={t}/>)}</div></section></div>}
